version: '3.8'
services:
  wuzzler-bot:
    build: .
    container_name: wuzzler-bot
    env_file:
      - .env
    environment:
      - MMR_DB_PATH=/app/db/mmr.db
    volumes:
      - mmr_db_data:/app/db
    restart: unless-stopped

volumes:
  mmr_db_data:
